[build]
builder      = "nixpacks"
buildCommand = "pip install ."

[deploy]
# Chain any DB migrations or codegen here:
preDeployCommand = ["prisma generate && prisma migrate deploy"]
startCommand      = "uvicorn main:app --host 0.0.0.0 --port $PORT"
